### ISSUE TITLE
On uniqueness of OpticalOscillator default names

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#14]
Related to issue #13. The solution to name by default is not robust in providing unique names for the models. As it stands now with the ```__del__``` method reducing by one the counter, when a model is deleted and a new one created then the two last created models share the same name.

There are two alternatives
1. To remove the -1 to the counter in the ```__del__``` method turning the counter into some sort of persistent and not updated index
2. We create a second variable to create a unique (persistent and not updated) index.

We should provide that if you work with a new session, the default names of models shouldn't clash. Of course if you export a model with a default name and then import it into an active session then you can as a user force the clash.

**Comment by francescorandi** [comment]
The standard choice in databases is to have a unique incremental index, i.e. your second alternative. However, I would not be worried about exporting/importing a model or an oscillator: the unique id would be a property of the object within its parent environment (an oscillator in a model or a model in a system), right? Therefore it would acquire one only at import. An intrinsic property could be a description in words. Or were you seeing it differently?

**Comment by ivergara** [comment]
In principle no unique id is needed, as each instance is unique. I was going more towards something for the end user to not get lost with oscillators with the same name in a model.

The question is, do we care for the naming and somewhat helping/forcing the user to be tidy or do we leave that responsibility to the end user. Actually, this is a question that we'll have to answer many times in different situations.

In this one, I'd leave the task to the end user to manage the oscillators in a model by using the optional name and description attributes of an oscillator. This instead of providing unique names for each created oscillator.
