### ISSUE TITLE
Environment file format

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#22]
When thinking about environments, they are definitely different than the optical models (see discussion #21) when thinking about saving them to disk.

There might be a disk memory use issue that is not relevant for optical models as they don't tend to be huge and are relatively simple. But environments could be very different.

Environments have a much more complex structure consisting of: models, (eventually) cached graphs, experimental data and relationships. In particular graphs and data can amount to considerable amount of data. For this something like pickling (or similar) the object could be a good idea.

Still, we can provide eventually for a text file like representation, using the same serialization protocol as the models for those who need/want/prefer such an option. In this case the cached graphs would be left out. And on top compression could be used.

**Comment by ivergara** [comment]
As you mention in the email, hdf5 is a good alternative!

Over pickle it has the advantage of being a general standard with third party tools to visualize them. It has python support, although not in the standard library. But if we're already asking for numpy, scipy, matplotlib, including hdf5 shouldn’t be a big deal. Worst case, if that module is not present the feature won't be available.

The only disadvantage over pickle that i see, is that it'll probably require some more work at the loading phase of the data.

**Comment by francescorandi** [comment]
I implemented the following:
In the OpticalSystem the save (and, reciprocally, the load) function opens the hdf5 file, creates the models and datasets subgroup (~subfolder inside the hdf file) and then passes the references to those subgroups to the savetohdf5 methods of the model and dataset classes, respectively. These methods can take as an argument either the reference to a subgroup in an already opened hdf file, or a string with the filename. In this way they can be used both to save everything from the system level and to separately save the dataset (or model) to an hdf5 file.
