### ISSUE TITLE
List of oscillators implemented

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#31]
There should be a way to easily ask the oscillators module which oscillators are implemented or at least loaded by default.
```python
> from Oscillators import *
> print(Oscillators)
[Drude, Gauss, Lorentz]
```
This with the aim to provide the user with an easy way to check which oscillators are available to work with.

**Comment by francescorandi** [comment]
I would say that we keep this simple since, as said, the number of lineshapes will converge very soon to the final value. In the branch single-osc-module I inserted a list() function in the __init__.py file of the Oscillators package returning this.

**Comment by ivergara** [comment]
For now looks like a fine solution. Will declare this issue as closed.
