### ISSUE TITLE
Energy units in dataset (default)

### ISSUE THREAD

**Issue by francescorandi** [francescorandi/optics#39]
I can't recall if we've already talked about this: Probably the most clean way to handle the datasets is to convert the x axis to electronvolts when loading the data (with convertX(), which then calls the relations.xtoeV() function) and to have all of them just in eV.
In order to have the x axis easily available in other units, I wrote the method xto(unitX). With such a method, plotting the dataset as a function of the wavelength in nanometers would look like

```python
import optics as o
os = o.system()
ds = os.addData(...)
#vs eV
plt.plot(ds.x, ds.y)
#vs nm
plt.plot(ds.xto('nm'), ds.y)
```

**Comment by ivergara** [comment]
It's fine.

One observation to the future: the plotting should be unit-aware, meaning that it should put the correct xlabel of the unit the dataset is being represented.
