### ISSUE TITLE
Oscillators without category

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#5]
There are "oscillators" that don't have family but that are necessary for constructing the model like the poles and epsilon_inf that need to be implemented.

These could be defined as "special" oscillator models so the program knows that they have some exceptions and particular conditions.

**Comment by francescorandi** [comment]
What are the exceptions and particular conditions? Don't they follow all the rules once you define them with their imaginary part equal to zero (or the corresponding for the particular case?)

**Comment by ivergara** [comment]
Yes, you're right. 

Although, for example, poles have to be out of the measured/interest range. This is something that the user might be responsible or the software could be aware of it at some level.
