### ISSUE TITLE
On energy units

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#6]
I believe, for simplicity we should stick to one energy unit namely eV throughout the software instead of having the flexibility to choose other energy units.

Now, at the level of importing datasets there might be the case where the energy unit is wavelength. We could opt and force the user to make the transformation before importing or we could handle it internally. My opinion is that we can make internally the change. 

A similar situation happens when exporting, which we could eventually could also support but I'd say it's a second order worry.

**Comment by francescorandi** [comment]
Yes, I would definitely stick to a single set of units within the software, allowing to import and export data with different units. There was some draft of how it could work at import in OpticalSystem.py. If you read the comments in OpticalSystem.py you can see that I initially thought it would be nice to have THz as frequency unit, as it is more SI than eV or cm-1. However, it may become cumbersome in some context. eV is probably a better choice for the photon energy axis. And I would like to avoid, from the depth of my heart, cm-1 ;)

**Comment by ivergara** [comment]
I'll check OpticalSystem.py. I also had some importing elements in my old stuff.

I also agree on avoiding cm-1, never liked it. But there are cases like the data from the FTIR we use here which comes in wavelength. Or if we want to eventually import current Refit models. Sure there are minor issues. THz might be more SI but eV is much more used in a broad sense for energy than THz. We can offer at some point THz, K, and cm-1 export capabilities at some point in the future but we base everything in eV in internal representations.
