### ISSUE TITLE
Python releases support

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#75]
I know we decided already to work on python 3, now the question from which version do we actively develop. Look at this https://github.com/numpy/numpy/pull/14086 we should follow that idea.

This means that we do now 3.5+ or even 3.6+, which is nice since then we could use some type annotations which I'm really enjoying and find them very useful for libraries.

**Comment by francescorandi** [comment]
Sure, we can go with the latest version. Given the library is still "young" (in terms of releases), I guess there is no point to stick to older releases of Python.
