### ISSUE TITLE
Improving oscillators structure and naming

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#9]
Now when importing the Oscillators module, there is too much namespace elements. For example creating an instance for Drude
```python
>>> import Oscillators
>>> Oscillators.Drude.Drude(1,1)
```
or
```python
>>> import Oscillators.Drude as D
>>> D.Drude(1,1)
```
Importing every available oscillator file on its own it's too cumbersome and not the idea to make it easy to extend.
Even when using
```python
>>> from Oscillators import *
>>> Drude.Drude(1,1)
```
results in cumbersome calls. 
Most likely the solution goes into the lines of modifying the __init__.py file.

**Comment by francescorandi** [comment]
Why not simply having a single file for the Oscillators module? The physical lineshapes are not so many to need a pleasingly extensible structure. If all the oscillator classes were in the same Oscillators.py file, then creating an instance of an oscillator would look like
`import Oscillators as osc
l = osc.Lorentz(1, 0.4, 2)
`
On the one hand, all oscillators should be considered for incorporation in the "official" Oscillators module. On the other, even if someone needs a user-defined alternative lineshapes, it still can still be used loading the appropriate module.

**Comment by ivergara** [comment]
That's the easy solution, but then the file will be rather huge containing: Drude, Lorentz, Gauss, Tauc-Lorentz, Sellmeier (pole). In this case the WVase definitions would be an user extended example.

I guess there must be a way to solve this issue without placing everything together.

Anyhow, you could do this and experiment with branching the source code, do the changes, test, and if we're happy merge back ;)

**Comment by francescorandi** [comment]
In the single-osc-module branch I modified the __init__.py file of the Oscillators package to make all the relevant names available in the top level of the package while keeping different files for different lineshapes. As shown in example_1.py in this branch, now 
`import Oscillators as osc
l = osc.Lorentz(1, 0.4, 2)`
works.

**Comment by ivergara** [comment]
Awesome! I knew that there should be an easy solution to what I wanted to do! But somehow never managed to implement it.

Then maybe you could reintegrate the branching to master and close this issue.

**Comment by ivergara** [comment]
Any reason to delete the plotting code in the example? I thought it was a nice thing to show the oscillator explicitly.

**Comment by francescorandi** [comment]
No, sorry, it was just a temporary change in the other branch and then I merged it with the master without noticing the change was still there. I restored those lines.
